version: "3.8"

services:
  sample:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
