version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
      - "/etc/letsencrypt/live/unirunners.ru/fullchain.pem:/etc/letsencrypt/live/unirunners.ru/fullchain.pem"
      - "/etc/letsencrypt/live/unirunners.ru/privkey.pem:/etc/letsencrypt/live/unirunners.ru/privkey.pem"
      - "/etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf"
      - "/etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem"
    ports:
      - 443:443
